services:
  mp-alerts-bot:
    build: .
    container_name: mp-alerts-bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN:-}
      ALERTS_TOKEN: ${ALERTS_TOKEN:-}
      TYESO_CHAT_ID: ${TYESO_CHAT_ID:-}
      BOUQ_CHAT_ID: ${BOUQ_CHAT_ID:-}
    ports:
      - "80:8000"
    restart: unless-stopped

  mp-alerts-configure:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["bot"]
    command: ["configure"]
    stdin_open: true
    tty: true
    restart: "no"
